### ISSUE TITLE
k3s agent and addvertise-address

### ISSUE THREAD

**Issue by golem1987** [garutilorenzo/k3s-aws-terraform-cluster#10]
it looks that on agent(worker) node we need cannot use --advertise-address flag anymore

https://docs.k3s.io/kr/cli/agent

**Comment by garutilorenzo** [comment]
This seems a copy/paste error. Checking doc history `--advertise-address` parameter was never available for the worker. I think this is not a problem since I had tested the code many times. I will remove it in a future release
