### ISSUE TITLE
How can I setup up Amazon Cloud Provider 

### ISSUE THREAD

**Issue by ashishworkspace** [garutilorenzo/k3s-aws-terraform-cluster#3]
I'm just getting started  with  k3s. 
My question is how can I setup this amazon cloud provider using your terraform code.
I followed this doc 👇but could not find the proper solution 
https://rancher.com/docs/rancher/v2.5/en/cluster-provisioning/rke-clusters/cloud-providers/amazon/
Can you please explain

**Comment by garutilorenzo** [comment]
This question is out of the scope of this repo, please ask support in rancher project
